### ISSUE TITLE
[PE-D][Tester B] Unexpected message when calling m list with modules on list.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-2/tp#230] opened 2022-10-29 04:17 UTC
Steps to reproduce:
1.Add one module to list
2. m list

![image.png](https://raw.githubusercontent.com/isanidiot/ped/main/files/b18dcf16-e851-4c21-a113-02835dbea8de.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: isanidiot/ped#1

**Comment by dlimyy** [comment] 2022-10-30 15:39
Duplicate of #209

**Closed by dlimyy** 2022-10-30 15:39 UTC
Labels: duplicate, Functionality Bug
